name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install modules
        run: yarn install --immutable
      - name: Run ESLint & Prettier
        run: yarn run lint
      - name: Check types
        run: yarn run generate && yarn run tsc

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: |
          git config user.name "O.A.F."
          git config user.email "<>"
      - run: yarn install --immutable
      - run: yarn run build
      - run: |
          git fetch --all
          mv KoLmafia KoLmafia-files
          mv build build-files
          if ! git switch release; then git switch --orphan release; fi
      - run: |
          rm -rf relay
          mkdir -p relay/yorick
          cp KoLmafia-files/relay/* relay/
          cp KoLmafia-files/relay/relay_YORICK.js relay/
          cp -R build-files/* relay/yorick/
      - run: |
          git add relay/
          {
            git commit -m "Build Mafia files for commit $GITHUB_SHA"
            git push origin release
          } || exit 0
